version: '3.4'

services:

  master_controller:
    image: skasip/eg4_master
    networks:
      - eg4_execution_control
    ports:
      - 5000:5000
    build: ./master_controller

  master_controller_db:
    image: mongo:3.7.1-jessie
    networks:
      - eg4_execution_control
    volumes:
      - master_db-data:/data/db
    ports:
      - 27017:27017

  processing_controller:
    image: skasip/eg4_pctl
    networks:
      - eg4_execution_control
    ports:
      - 5000:5000
    build: ./processing_controller

  processing_controller_db:
    image: mongo:3.7.1-jessie
    networks:
      - eg4_execution_control
    volumes:
      - processing_controller_db-data:/data/db

  message_queue:
    image: rabbitmq:3.7.2-alpine
    networks:
      - eg4_execution_control
    ports:
      - 5672:5672

volumes:
  master_db-data:
  processing_controller_db-data:

networks:
  eg4_execution_control:
